language: node_js
node_js:
- stable
jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run test
    - stage: deploy
      deploy:
        provider: script
        script: npm run deploy
        skip_cleanup: true
        on:
          branch: master
